//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CameraControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraControls"",
    ""maps"": [
        {
            ""name"": ""CameraSelection"",
            ""id"": ""a8f6c2d1-3b4e-4f5a-8c9d-1e2f3a4b5c6d"",
            ""actions"": [
                {
                    ""name"": ""SelectCamera1"",
                    ""type"": ""Button"",
                    ""id"": ""1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCamera2"",
                    ""type"": ""Button"",
                    ""id"": ""2a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCamera3"",
                    ""type"": ""Button"",
                    ""id"": ""3a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCamera4"",
                    ""type"": ""Button"",
                    ""id"": ""4a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCamera5"",
                    ""type"": ""Button"",
                    ""id"": ""5a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCamera6"",
                    ""type"": ""Button"",
                    ""id"": ""6a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCamera6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CameraSelection
        m_CameraSelection = asset.FindActionMap("CameraSelection", throwIfNotFound: true);
        m_CameraSelection_SelectCamera1 = m_CameraSelection.FindAction("SelectCamera1", throwIfNotFound: true);
        m_CameraSelection_SelectCamera2 = m_CameraSelection.FindAction("SelectCamera2", throwIfNotFound: true);
        m_CameraSelection_SelectCamera3 = m_CameraSelection.FindAction("SelectCamera3", throwIfNotFound: true);
        m_CameraSelection_SelectCamera4 = m_CameraSelection.FindAction("SelectCamera4", throwIfNotFound: true);
        m_CameraSelection_SelectCamera5 = m_CameraSelection.FindAction("SelectCamera5", throwIfNotFound: true);
        m_CameraSelection_SelectCamera6 = m_CameraSelection.FindAction("SelectCamera6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraSelection
    private readonly InputActionMap m_CameraSelection;
    private List<ICameraSelectionActions> m_CameraSelectionActionsCallbackInterfaces = new List<ICameraSelectionActions>();
    private readonly InputAction m_CameraSelection_SelectCamera1;
    private readonly InputAction m_CameraSelection_SelectCamera2;
    private readonly InputAction m_CameraSelection_SelectCamera3;
    private readonly InputAction m_CameraSelection_SelectCamera4;
    private readonly InputAction m_CameraSelection_SelectCamera5;
    private readonly InputAction m_CameraSelection_SelectCamera6;
    public struct CameraSelectionActions
    {
        private @CameraControls m_Wrapper;
        public CameraSelectionActions(@CameraControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectCamera1 => m_Wrapper.m_CameraSelection_SelectCamera1;
        public InputAction @SelectCamera2 => m_Wrapper.m_CameraSelection_SelectCamera2;
        public InputAction @SelectCamera3 => m_Wrapper.m_CameraSelection_SelectCamera3;
        public InputAction @SelectCamera4 => m_Wrapper.m_CameraSelection_SelectCamera4;
        public InputAction @SelectCamera5 => m_Wrapper.m_CameraSelection_SelectCamera5;
        public InputAction @SelectCamera6 => m_Wrapper.m_CameraSelection_SelectCamera6;
        public InputActionMap Get() { return m_Wrapper.m_CameraSelection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraSelectionActions set) { return set.Get(); }
        public void AddCallbacks(ICameraSelectionActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraSelectionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraSelectionActionsCallbackInterfaces.Add(instance);
            @SelectCamera1.started += instance.OnSelectCamera1;
            @SelectCamera1.performed += instance.OnSelectCamera1;
            @SelectCamera1.canceled += instance.OnSelectCamera1;
            @SelectCamera2.started += instance.OnSelectCamera2;
            @SelectCamera2.performed += instance.OnSelectCamera2;
            @SelectCamera2.canceled += instance.OnSelectCamera2;
            @SelectCamera3.started += instance.OnSelectCamera3;
            @SelectCamera3.performed += instance.OnSelectCamera3;
            @SelectCamera3.canceled += instance.OnSelectCamera3;
            @SelectCamera4.started += instance.OnSelectCamera4;
            @SelectCamera4.performed += instance.OnSelectCamera4;
            @SelectCamera4.canceled += instance.OnSelectCamera4;
            @SelectCamera5.started += instance.OnSelectCamera5;
            @SelectCamera5.performed += instance.OnSelectCamera5;
            @SelectCamera5.canceled += instance.OnSelectCamera5;
            @SelectCamera6.started += instance.OnSelectCamera6;
            @SelectCamera6.performed += instance.OnSelectCamera6;
            @SelectCamera6.canceled += instance.OnSelectCamera6;
        }

        private void UnregisterCallbacks(ICameraSelectionActions instance)
        {
            @SelectCamera1.started -= instance.OnSelectCamera1;
            @SelectCamera1.performed -= instance.OnSelectCamera1;
            @SelectCamera1.canceled -= instance.OnSelectCamera1;
            @SelectCamera2.started -= instance.OnSelectCamera2;
            @SelectCamera2.performed -= instance.OnSelectCamera2;
            @SelectCamera2.canceled -= instance.OnSelectCamera2;
            @SelectCamera3.started -= instance.OnSelectCamera3;
            @SelectCamera3.performed -= instance.OnSelectCamera3;
            @SelectCamera3.canceled -= instance.OnSelectCamera3;
            @SelectCamera4.started -= instance.OnSelectCamera4;
            @SelectCamera4.performed -= instance.OnSelectCamera4;
            @SelectCamera4.canceled -= instance.OnSelectCamera4;
            @SelectCamera5.started -= instance.OnSelectCamera5;
            @SelectCamera5.performed -= instance.OnSelectCamera5;
            @SelectCamera5.canceled -= instance.OnSelectCamera5;
            @SelectCamera6.started -= instance.OnSelectCamera6;
            @SelectCamera6.performed -= instance.OnSelectCamera6;
            @SelectCamera6.canceled -= instance.OnSelectCamera6;
        }

        public void RemoveCallbacks(ICameraSelectionActions instance)
        {
            if (m_Wrapper.m_CameraSelectionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraSelectionActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraSelectionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraSelectionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraSelectionActions @CameraSelection => new CameraSelectionActions(this);
    public interface ICameraSelectionActions
    {
        void OnSelectCamera1(InputAction.CallbackContext context);
        void OnSelectCamera2(InputAction.CallbackContext context);
        void OnSelectCamera3(InputAction.CallbackContext context);
        void OnSelectCamera4(InputAction.CallbackContext context);
        void OnSelectCamera5(InputAction.CallbackContext context);
        void OnSelectCamera6(InputAction.CallbackContext context);
    }
}
